// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ChatForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"chat-form\" class=\"w-full rounded-b-lg pb-2 px-2 flex gap-1 items-end\" hx-post=\"/chat/messages\" hx-trigger=\"submit\" hx-target=\"#messages\" hx-swap=\"beforeend\" hx-swap-oob=\"outerHTML:#chat-form\"><textarea type=\"text\" name=\"message\" id=\"message\" oninput=\"this.style.height = &#39;&#39;;this.style.height = Math.min(this.scrollHeight+2, 136) + &#39;px&#39;\" class=\"w-full h-11 border border-slate-300 rounded-lg text-base p-2 resize-none overflow-y-auto\"></textarea> <button type=\"submit\" id=\"submit\" class=\"h-11 bg-blue-500 hover:bg-blue-600 active:bg-blue-700 transition-all text-white px-3 rounded-lg\">Send</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
