apiVersion: v1
kind: Secret
metadata:
  name: ask-alex-secrets
  labels:
    app: { { .Release.Name } }
type: Opaque
stringData:
  # PostgreSQL connection string
  pg-conn-str: { { .Values.secrets.pgConnStr | quote } }
  # OpenRouter API key for LLM access
  openrouter-api-key: { { .Values.secrets.openrouterApiKey | quote } }
  # Frontend URL for CORS
  frontend-url: { { .Values.secrets.frontendUrl | quote } }
